// Generated by https://quicktype.io

export interface Currencies {
  item: Item;
  refIndex: number;
}

export interface Item {
  id: string;
  currency: string;
  symbol: string;
  name: string;
  logo_url: string;
  status: Status;
  platform_currency?: string;
  price: string;
  price_date: string;
  price_timestamp: string;
  circulating_supply: string;
  max_supply?: string;
  market_cap: string;
  market_cap_dominance: string;
  num_exchanges: string;
  num_pairs: string;
  num_pairs_unmapped: string;
  first_candle: string;
  first_trade: string;
  first_order_book: string;
  rank: string;
  rank_delta: string;
  high: string;
  high_timestamp: string;
  "1d": The1_D;
  "7d": The1_D;
  "30d": The1_D;
  "365d": The1_D;
  ytd: The1_D;
  first_priced_at?: string;
}

export interface The1_D {
  volume: string;
  price_change: string;
  price_change_pct: string;
  volume_change?: string;
  volume_change_pct?: string;
  market_cap_change?: string;
  market_cap_change_pct?: string;
}

export enum Status {
  Active = "active",
}
